# Generated by Django 5.1.6 on 2025-03-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0004_remove_promocode_used_count_promocode_current_uses_and_more'),
        ('users', '0005_profile_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promocode.promocode'),
        ),
    ]
