# Generated by Django 5.1.6 on 2025-03-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={},
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(default=1, verbose_name='Процент скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Минимальная сумма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(verbose_name='Максимальное использование'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocode.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promo_code')},
            },
        ),
    ]
