# Generated by Django 5.1.6 on 2025-03-19 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0002_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Мин. сумма заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное использование'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано раз'),
        ),
        migrations.DeleteModel(
            name='PromoCodeUsage',
        ),
    ]
