# Generated by Django 5.1.6 on 2025-03-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0003_remove_promocode_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='used_count',
        ),
        migrations.AddField(
            model_name='promocode',
            name='current_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущее количество использований'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveIntegerField(verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(verbose_name='Максимальное количество использований'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма заказа'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promocode.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promo_code')},
            },
        ),
    ]
